# Generated by Django 4.2.4 on 2023-08-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='apellido',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='codigo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('COLABORADOR', 'COLABORADOR'), ('LECTURA', 'LECTURA')], default='LECTURA', max_length=12),
        ),
    ]
