# Generated by Django 4.2.4 on 2023-08-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_colaborador_apellido_colaborador_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='codigo',
            field=models.CharField(max_length=3),
        ),
    ]
