# Generated by Django 4.2.4 on 2023-08-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_colaborador_apellido_colaborador_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='codigo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('COLABORADOR', 'COLABORADOR'), ('LECTURA', 'LECTURA')], default='LECTURA', max_length=12),
        ),
    ]
