# Generated by Django 4.2.4 on 2023-08-19 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_colaborador_codigo_colaborador_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='foto',
        ),
    ]
