# Generated by Django 4.1.7 on 2023-05-18 18:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('farmacias', '0001_initial'),
        ('servicios', '0001_initial'),
        ('clientes', '0001_initial'),
        ('observaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('costo_proveedor', models.FloatField(default=0)),
                ('deposito', models.FloatField(default=0)),
                ('costo', models.FloatField(default=0)),
                ('senia', models.FloatField(default=0)),
                ('falta_abonar', models.FloatField(default=0)),
                ('pagado', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('Suspendido', 'Suspendido'), ('Cerrado', 'Cerrado'), ('En Proceso', 'En Proceso'), ('Presupuesto', 'Presupuesto')], max_length=40)),
                ('fecha_vencimento', models.DateField(blank=True, default=datetime.date(2023, 5, 18), null=True)),
                ('entregado_proveedor', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colaboradores.colaborador')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacias.farmacia')),
                ('observaciones', models.ManyToManyField(to='observaciones.observacion')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
        ),
    ]
