# Generated by Django 4.1.7 on 2023-05-23 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='costo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='costo_proveedor',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='delivery',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='deposito',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='entregado_proveedor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='estado',
            field=models.CharField(blank=True, choices=[('Abierto', 'Abierto'), ('Suspendido', 'Suspendido'), ('Cerrado', 'Cerrado'), ('En Proceso', 'En Proceso'), ('Presupuesto', 'Presupuesto')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='falta_abonar',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='fecha_vencimento',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 23), null=True),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='pagado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='senia',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
