# Generated by Django 4.1.7 on 2023-05-23 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0002_alter_protocolo_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 22, 58, 3, 446413, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='fecha_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
