# Generated by Django 4.1.7 on 2023-08-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0004_alter_protocolo_options_alter_protocolo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
