# Generated by Django 4.2.4 on 2023-08-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='tachado',
            field=models.BooleanField(default=False),
        ),
    ]
